# Generated by Django 5.0.7 on 2024-12-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenentapp', '0006_wishlist_added_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
